<div class="container">
    <div class="row">
        <div class="col-12">
            <nav class="main-nav">

            <!-- ***** Logo Start ***** -->
            <img src="assets/images/logo.png" class="header-image" alt="DTeaches Logo" onclick="window.location.href='index.php';">
            <!-- ***** Logo End ***** -->
            <a href="index.php" class="logo">
                <h1>D<span style="color:rgba(255, 255, 255, 0.75);">Teaches</span></h1>
            </a>

            <!-- ***** Menu Start ***** -->
            <ul class="nav">
                <li class="scroll-to-section"><a href="#contact" style="font-weight: 600;">COMEÇAR JÁ</a></li>
                <li class="scroll-to-section"><a href="login.php" style="font-weight: 600;">LOGIN</a></li>
            </ul>
            <!-- ***** Menu End ***** -->
            </nav>
        </div>
    </div>
</div>