<div class="NbGcm">
  <div class="_3vDrO">
    <div class="_3I51r _2OF7V">
      <span class="oboa9 _3viv6 HCWXf _3PU7E _3JPjo" style="margin-right: 5px;"></span><span class="_1icRZ _1k9o2 cCL9P"></span>
    </div>
    <div class="_1ALvM"></div>
    <div class="_1G4t1 _3HsQj _2OF7V" data-test="user-dropdown">
      <span class="_3ROGm"><img class="_3Kp8s" src="../assets/images/user2.png" alt="Avatar"></span>
      <span style="margin-left:-5px;"><?php echo htmlspecialchars($username); ?></span>
      <span class="_2Vgy6 _1k0u2 cCL9P"></span>
      <ul class="_3q7Wh OSaWc _2HujR _1ZY-H">
        <li class="_31ObI _1qBnH">
          <a href="perfil.php" class="_3sWvR">Perfil</a>
        </li>
        <li class="_31ObI _1qBnH">
          <a href="editarperfil.php" class="_3sWvR">Editar Perfil</a>
        </li>
        <li class="_31ObI _1qBnH">
          <a href="logout.php" class="_3sWvR">Sair</a>
        </li>
      </ul>
    </div>
  </div>
  <a href="indexuser.php" class="logo">
  <h1>D<span style="line-height: 1.2; color: rgba(255, 255, 255, 0.75);">Teaches</span></h1>
  </a>
</div>